// whitespace
whitespace = _{ " " | "\t" | "\r" | "\n" }
linesep = _{ "\n" | ";" }

// module for files
module = { soi ~ decl? ~ (linesep ~ decl)* ~ eoi }
// stmt for the command-line
stmt = { expr }

decl = { decl_fn | decl_struct }
decl_fn = { "fn" ~ ident ~ "(" ~ ")" ~ "=" ~ expr }
decl_struct = { "struct" }

expr = { "lol" }

// ident
all_chars = _{ 'a'..'z' | 'A'..'Z' | "_" | '0'..'9' }
ident = @{ ('a'..'z' | 'A'..'Z' | "_") ~ all_chars* }
